version: "3.6"

services: 
  onlyoffice-communityserver-ami:
    build:
      context: ./
      dockerfile: Dockerfile.all
      target: communityserver-ami
    image: "${REPO}/${STATUS}communityserver:${TAG}"
     
  onlyoffice-communityserver-alc:
    build:
      context: ./
      dockerfile: Dockerfile.all
      target: communityserver-alc
    image: "${REPO}/${STATUS}communityserver:${TAG}-alc"
    